name: Deploy to Production

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - production

env:
  REGISTRY: ghcr.io
  IMAGE_NAME_API: ${{ github.repository }}/api
  IMAGE_NAME_WEB: ${{ github.repository }}/web

jobs:
  deploy:
    name: Deploy to ${{ github.event.inputs.environment || 'production' }}
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment || 'production' }}
    permissions:
      contents: read
      packages: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy to server
        run: |
          echo "🚀 Deploying to ${{ github.event.inputs.environment || 'production' }}"
          echo "This would typically:"
          echo "1. Pull the latest Docker images"
          echo "2. Update docker-compose.yml with new image tags"
          echo "3. Run database migrations"
          echo "4. Restart services with zero downtime"
          echo "5. Run health checks"
          echo "6. Send notifications"

      - name: Health check
        run: |
          echo "🏥 Running health checks..."
          echo "API health check would go here"
          echo "Web health check would go here"

      - name: Notify deployment
        run: |
          echo "📢 Deployment completed successfully!"
          echo "Environment: ${{ github.event.inputs.environment || 'production' }}"
          echo "Version: ${{ github.sha }}"
